drop table MEMBER;
drop table CUSTOMER_DETAIL;
drop table REGISTER_DETAIL;
drop table ADMIN_DETAIL;
drop table HOUSE;
drop table REGIST_HOUSE;
drop table REPORT;
drop table QEUSTION;

  CREATE TABLE "POJO"."MEMBER" 
   (	"MEM_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"MEM_NAME" VARCHAR2(30 BYTE), 
	"MEM_PHONE" NUMBER(30,0), 
	"MEM_PASSWORD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "POJO"."CUSTOMER_DETAIL" 
   (	"CUS_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"CUS_EMAIL" VARCHAR2(50 BYTE), 
	"CUS_GENDER" VARCHAR2(10 BYTE), 
	"CUS_IMG" BLOB, 
	"CUS_INTRO" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CUS_IMG") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  CREATE TABLE "POJO"."REGISTER_DETAIL" 
   (	"REGIST_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"REGIST_EMAIL" VARCHAR2(40 BYTE), 
  "REGIST_GENDER" VARCHAR2(10 BYTE), 
	"REGIST_IMG" BLOB,
  "REGIST_INTRO" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("REGIST_IMG") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  CREATE TABLE "POJO"."ADMIN_DETAIL" 
   (	"ADMIN_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"ADMIN_GRADE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "POJO"."HOUSE" 
   (	"HOUSE_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"HOUSE_NAME" VARCHAR2(40 BYTE), 
	"HOUSE_ADDR" VARCHAR2(100 BYTE), 
	"HOUSE_PRICE" NUMBER(38,0), 
	"HOUSE_SCORE" NUMBER(38,0), 
	"HOUSE_INFO" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "POJO"."REGIST_HOUSE" 
   (	"RH_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"CHECK_IN" DATE, 
	"CHECK_OUT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "POJO"."QEUSTION" 
   (	"QUEST_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"QUEST_TITLE" VARCHAR2(50 BYTE), 
	"QUEST_CONTENT" VARCHAR2(400 BYTE), 
	"QUEST_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "POJO"."REPORT" 
   (	"REPORT_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"CONTENT" VARCHAR2(400 BYTE), 
	"REPORT_CUS_NAME" VARCHAR2(40 BYTE), 
	"REGIT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  insert into MEMBER values(1, 'hong', 01012344567, 1234);
  insert into CUSTOMER_DETAIL values (1, 'abc@naver.com', 'male', null, 'hello');
  insert into REGISTER_DETAIL values (1, 'abc@naver.com', 'male', null, 'hello');
  insert into ADMIN_DETAIL values (99, '최고관리자');
  insert into HOUSE values (1, '공주빌라', '천안시 서북구 두정동', 350000, 8, 'hello');
  insert into QEUSTION values (1, '신고합니다', '신고합니다 병장 양희준', sysdate);
  insert into REGIST_HOUSE values (1, '2016/09/25', '2016/09/30');
  insert into REPORT values (1, '피해사례', '사기당했어요', '홍길동', sysdate);
