package pojo.web.dto;

import java.io.Serializable;

/**
 * HOUSE 모델 클래스.
 * 
 * @author generated by ERMaster 
 * @version $Id$
 */
public class House implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** HOUSE_NO. */
	private Integer houseNo;

	/** HOUSE_NAME. */
	private String houseName;

	/** HOUSE_ADDRESS. */
	private String houseAddress;

	/** HOUSE_PRICE. */
	private Integer housePrice;

	/** HOUSE_SCORE. */
	private Integer houseScore;

	/** HOUSE_INFO. */
	private String houseInfo;
	
	/** REGIST_HOUSE */
	private RegistHouse registHouse;

	public RegistHouse getRegistHouse() {
		return registHouse;
	}

	public void setRegistHouse(RegistHouse registHouse) {
		this.registHouse = registHouse;
	}

	/**
	 * 생성자.
	 */
	public House() {
	}

	public House(Integer houseNo, String houseName, String houseAddress, Integer housePrice, Integer houseScore,
			String houseInfo) {
		super();
		this.houseNo = houseNo;
		this.houseName = houseName;
		this.houseAddress = houseAddress;
		this.housePrice = housePrice;
		this.houseScore = houseScore;
		this.houseInfo = houseInfo;
	}

	/**
	 * HOUSE_NO을 설정합니다..
	 * 
	 * @param houseNo
	 *            HOUSE_NO
	 */
	public void setHouseNo(Integer houseNo) {
		this.houseNo = houseNo;
	}

	/**
	 * HOUSE_NO을 가져옵니다..
	 * 
	 * @return HOUSE_NO
	 */
	public Integer getHouseNo() {
		return this.houseNo;
	}

	/**
	 * HOUSE_NAME을 설정합니다..
	 * 
	 * @param houseName
	 *            HOUSE_NAME
	 */
	public void setHouseName(String houseName) {
		this.houseName = houseName;
	}

	/**
	 * HOUSE_NAME을 가져옵니다..
	 * 
	 * @return HOUSE_NAME
	 */
	public String getHouseName() {
		return this.houseName;
	}

	/**
	 * HOUSE_ADDRESS을 설정합니다..
	 * 
	 * @param houseAddress
	 *            HOUSE_ADDRESS
	 */
	public void setHouseAddress(String houseAddress) {
		this.houseAddress = houseAddress;
	}

	/**
	 * HOUSE_ADDRESS을 가져옵니다..
	 * 
	 * @return HOUSE_ADDRESS
	 */
	public String getHouseAddress() {
		return this.houseAddress;
	}

	/**
	 * HOUSE_PRICE을 설정합니다..
	 * 
	 * @param housePrice
	 *            HOUSE_PRICE
	 */
	public void setHousePrice(Integer housePrice) {
		this.housePrice = housePrice;
	}

	/**
	 * HOUSE_PRICE을 가져옵니다..
	 * 
	 * @return HOUSE_PRICE
	 */
	public Integer getHousePrice() {
		return this.housePrice;
	}

	/**
	 * HOUSE_SCORE을 설정합니다..
	 * 
	 * @param houseScore
	 *            HOUSE_SCORE
	 */
	public void setHouseScore(Integer houseScore) {
		this.houseScore = houseScore;
	}

	/**
	 * HOUSE_SCORE을 가져옵니다..
	 * 
	 * @return HOUSE_SCORE
	 */
	public Integer getHouseScore() {
		return this.houseScore;
	}

	/**
	 * HOUSE_INFO을 설정합니다..
	 * 
	 * @param houseInfo
	 *            HOUSE_INFO
	 */
	public void setHouseInfo(String houseInfo) {
		this.houseInfo = houseInfo;
	}

	/**
	 * HOUSE_INFO을 가져옵니다..
	 * 
	 * @return HOUSE_INFO
	 */
	public String getHouseInfo() {
		return this.houseInfo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((houseNo == null) ? 0 : houseNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		House other = (House) obj;
		if (houseNo == null) {
			if (other.houseNo != null) {
				return false;
			}
		} else if (!houseNo.equals(other.houseNo)) {
			return false;
		}
		return true;
	}
	
	@Override
	public String toString() {
		return "House [houseNo=" + houseNo + ", houseName=" + houseName + ", houseAddress=" + houseAddress
				+ ", housePrice=" + housePrice + ", houseScore=" + houseScore + ", houseInfo=" + houseInfo + "]";
	}

}
