package pojo.web.dto;
import java.io.Serializable;

/**
 * MEMBER 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Member implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** MEM_ID. */
	private Integer memId;

	/** MEM_NAME. */
	private String memName;

	/** MEM_PHONE. */
	private Integer memPhone;

	/** MEM_PASSWORD. */
	private String memPassword;

	/**
	 * 생성자.
	 */
	public Member() {
	}

	/**
	 * MEM_ID을 설정합니다..
	 * 
	 * @param memId
	 *            MEM_ID
	 */
	public void setMemId(Integer memId) {
		this.memId = memId;
	}

	/**
	 * MEM_ID을 가져옵니다..
	 * 
	 * @return MEM_ID
	 */
	public Integer getMemId() {
		return this.memId;
	}

	/**
	 * MEM_NAME을 설정합니다..
	 * 
	 * @param memName
	 *            MEM_NAME
	 */
	public void setMemName(String memName) {
		this.memName = memName;
	}

	/**
	 * MEM_NAME을 가져옵니다..
	 * 
	 * @return MEM_NAME
	 */
	public String getMemName() {
		return this.memName;
	}

	/**
	 * MEM_PHONE을 설정합니다..
	 * 
	 * @param memPhone
	 *            MEM_PHONE
	 */
	public void setMemPhone(Integer memPhone) {
		this.memPhone = memPhone;
	}

	/**
	 * MEM_PHONE을 가져옵니다..
	 * 
	 * @return MEM_PHONE
	 */
	public Integer getMemPhone() {
		return this.memPhone;
	}

	/**
	 * MEM_PASSWORD을 설정합니다..
	 * 
	 * @param memPassword
	 *            MEM_PASSWORD
	 */
	public void setMemPassword(String memPassword) {
		this.memPassword = memPassword;
	}

	/**
	 * MEM_PASSWORD을 가져옵니다..
	 * 
	 * @return MEM_PASSWORD
	 */
	public String getMemPassword() {
		return this.memPassword;
	}


}
