package pojo.web.dto;

import java.io.Serializable;
import java.sql.Blob;

/**
 * MEMBER 모델 클래스.
 * 
 * @author generated by ERMaster 
 * @version $Id$
 */
public class Member implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** MEM_ID. */
	private String memId;

	/** MEM_NAME. */
	private String memName;

	/** MEM_PASSWORD. */
	private String memPassword;

	/** MEM_PHONE. */
	private Integer memPhone;

	/** MEM_EMAIL. */
	private String memEmail;

	/** MEM_GENDER. */
	private String memGender;

	/** MEM_IMG. */
	// Data Type 다시 생각해보기
	private Blob memImg;

	/** MEM_INTRO. */
	private String memIntro;
	
	/** CUSTOMER_DETAIL */
	private CustomerDetail customerDetail;
	
	/** REGISTER_DETAIL */
	private RegisterDetail registerDetail;
	
	/** ADMIN_DETAIL */
	private AdminDetail adminDetail;

	public CustomerDetail getCustomerDetail() {
		return customerDetail;
	}

	public void setCustomerDetail(CustomerDetail customerDetail) {
		this.customerDetail = customerDetail;
	}

	public RegisterDetail getRegisterDetail() {
		return registerDetail;
	}

	public void setRegisterDetail(RegisterDetail registerDetail) {
		this.registerDetail = registerDetail;
	}

	public AdminDetail getAdminDetail() {
		return adminDetail;
	}

	public void setAdminDetail(AdminDetail adminDetail) {
		this.adminDetail = adminDetail;
	}

	/**
	 * 생성자.
	 */
	public Member() {
	}

	/**
	 * MEM_ID을 설정합니다..
	 * 
	 * @param memId
	 *            MEM_ID
	 */
	public void setMemId(String memId) {
		this.memId = memId;
	}

	/**
	 * MEM_ID을 가져옵니다..
	 * 
	 * @return MEM_ID
	 */
	public String getMemId() {
		return this.memId;
	}

	/**
	 * MEM_NAME을 설정합니다..
	 * 
	 * @param memName
	 *            MEM_NAME
	 */
	public void setMemName(String memName) {
		this.memName = memName;
	}

	/**
	 * MEM_NAME을 가져옵니다..
	 * 
	 * @return MEM_NAME
	 */
	public String getMemName() {
		return this.memName;
	}

	/**
	 * MEM_PASSWORD을 설정합니다..
	 * 
	 * @param memPassword
	 *            MEM_PASSWORD
	 */
	public void setMemPassword(String memPassword) {
		this.memPassword = memPassword;
	}

	/**
	 * MEM_PASSWORD을 가져옵니다..
	 * 
	 * @return MEM_PASSWORD
	 */
	public String getMemPassword() {
		return this.memPassword;
	}

	/**
	 * MEM_PHONE을 설정합니다..
	 * 
	 * @param memPhone
	 *            MEM_PHONE
	 */
	public void setMemPhone(Integer memPhone) {
		this.memPhone = memPhone;
	}

	/**
	 * MEM_PHONE을 가져옵니다..
	 * 
	 * @return MEM_PHONE
	 */
	public Integer getMemPhone() {
		return this.memPhone;
	}

	/**
	 * MEM_EMAIL을 설정합니다..
	 * 
	 * @param memEmail
	 *            MEM_EMAIL
	 */
	public void setMemEmail(String memEmail) {
		this.memEmail = memEmail;
	}

	/**
	 * MEM_EMAIL을 가져옵니다..
	 * 
	 * @return MEM_EMAIL
	 */
	public String getMemEmail() {
		return this.memEmail;
	}

	/**
	 * MEM_GENDER을 설정합니다..
	 * 
	 * @param memGender
	 *            MEM_GENDER
	 */
	public void setMemGender(String memGender) {
		this.memGender = memGender;
	}

	/**
	 * MEM_GENDER을 가져옵니다..
	 * 
	 * @return MEM_GENDER
	 */
	public String getMemGender() {
		return this.memGender;
	}

	/**
	 * MEM_IMG을 설정합니다..
	 * 
	 * @param memImg
	 *            MEM_IMG
	 */
	public void setMemImg(Blob memImg) {
		this.memImg = memImg;
	}

	/**
	 * MEM_IMG을 가져옵니다..
	 * 
	 * @return MEM_IMG
	 */
	public Blob getMemImg() {
		return this.memImg;
	}

	/**
	 * MEM_INTRO을 설정합니다..
	 * 
	 * @param memIntro
	 *            MEM_INTRO
	 */
	public void setMemIntro(String memIntro) {
		this.memIntro = memIntro;
	}

	/**
	 * MEM_INTRO을 가져옵니다..
	 * 
	 * @return MEM_INTRO
	 */
	public String getMemIntro() {
		return this.memIntro;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((memId == null) ? 0 : memId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Member other = (Member) obj;
		if (memId == null) {
			if (other.memId != null) {
				return false;
			}
		} else if (!memId.equals(other.memId)) {
			return false;
		}
		return true;
	}

}
