package pojo.web.dto;

import java.io.Serializable;

/**
 * MEMBER_DETAIL 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class MemberDetail implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** DETAIL_ID. */
	private Integer detailId;

	/** DETAIL_GRADE. */
	private String detailGrade;

	/**
	 * 생성자.
	 */
	public MemberDetail() {
	}

	/**
	 * DETAIL_ID을 설정합니다..
	 * 
	 * @param detailId
	 *            DETAIL_ID
	 */
	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	/**
	 * DETAIL_ID을 가져옵니다..
	 * 
	 * @return DETAIL_ID
	 */
	public Integer getDetailId() {
		return this.detailId;
	}

	/**
	 * DETAIL_GRADE을 설정합니다..
	 * 
	 * @param detailGrade
	 *            DETAIL_GRADE
	 */
	public void setDetailGrade(String detailGrade) {
		this.detailGrade = detailGrade;
	}

	/**
	 * DETAIL_GRADE을 가져옵니다..
	 * 
	 * @return DETAIL_GRADE
	 */
	public String getDetailGrade() {
		return this.detailGrade;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((detailId == null) ? 0 : detailId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		MemberDetail other = (MemberDetail) obj;
		if (detailId == null) {
			if (other.detailId != null) {
				return false;
			}
		} else if (!detailId.equals(other.detailId)) {
			return false;
		}
		return true;
	}

}
