package pojo.web.dto;
import java.io.Serializable;
import java.util.Date;
import java.util.Set;

/**
 * QEUSTION 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Qeustion implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** QUEST_NO. */
	private Integer questNo;

	/** QUEST_TITLE. */
	private String questTitle;

	/** QUEST_CONTENT. */
	private String questContent;

	/** QUEST_DATE. */
	private Date questDate;
	
	/** MEMBER */
	private Member member;
	
	private Set<Member> memberSet;

	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Set<Member> getMemberSet() {
		return memberSet;
	}

	public void setMemberSet(Set<Member> memberSet) {
		this.memberSet = memberSet;
	}

	/**
	 * 생성자.
	 */
	public Qeustion() {
	}

	/**
	 * QUEST_NO을 설정합니다..
	 * 
	 * @param questNo
	 *            QUEST_NO
	 */
	public void setQuestNo(Integer questNo) {
		this.questNo = questNo;
	}

	/**
	 * QUEST_NO을 가져옵니다..
	 * 
	 * @return QUEST_NO
	 */
	public Integer getQuestNo() {
		return this.questNo;
	}

	/**
	 * QUEST_TITLE을 설정합니다..
	 * 
	 * @param questTitle
	 *            QUEST_TITLE
	 */
	public void setQuestTitle(String questTitle) {
		this.questTitle = questTitle;
	}

	/**
	 * QUEST_TITLE을 가져옵니다..
	 * 
	 * @return QUEST_TITLE
	 */
	public String getQuestTitle() {
		return this.questTitle;
	}

	/**
	 * QUEST_CONTENT을 설정합니다..
	 * 
	 * @param questContent
	 *            QUEST_CONTENT
	 */
	public void setQuestContent(String questContent) {
		this.questContent = questContent;
	}

	/**
	 * QUEST_CONTENT을 가져옵니다..
	 * 
	 * @return QUEST_CONTENT
	 */
	public String getQuestContent() {
		return this.questContent;
	}

	/**
	 * QUEST_DATE을 설정합니다..
	 * 
	 * @param questDate
	 *            QUEST_DATE
	 */
	public void setQuestDate(Date questDate) {
		this.questDate = questDate;
	}

	/**
	 * QUEST_DATE을 가져옵니다..
	 * 
	 * @return QUEST_DATE
	 */
	public Date getQuestDate() {
		return this.questDate;
	}


}
