package pojo.web.dto;
import java.io.Serializable;

/**
 * REGIST_HOUSE 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RegistHouse implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** RH_NO. */
	private Integer rhNo;

	/**
	 * 생성자.
	 */
	public RegistHouse() {
	}

	/**
	 * RH_NO을 설정합니다..
	 * 
	 * @param rhNo
	 *            RH_NO
	 */
	public void setRhNo(Integer rhNo) {
		this.rhNo = rhNo;
	}

	/**
	 * RH_NO을 가져옵니다..
	 * 
	 * @return RH_NO
	 */
	public Integer getRhNo() {
		return this.rhNo;
	}


}
