package pojo.web.dto;
import java.io.Serializable;
import java.sql.Blob;
import java.util.Set;

/**
 * REGISTER_DETAIL 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RegisterDetail implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** REGIST_ID. */
	private Integer registId;

	/** REGIST_EMAIL. */
	private String registEmail;

	/** REGIST_GENDER. */
	private String registGender;

	/** REGIST_IMG. */
	private Blob registImg;

	/** REGIST_INTRO. */
	private String registIntro;
	
	/** MEMBER */
	private Member member;
	
	private Set<Member> memberSet;
	
	public Set<Member> getMemberSet() {
		return memberSet;
	}

	public void setMemberSet(Set<Member> memberSet) {
		this.memberSet = memberSet;
	}

	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	/**
	 * 생성자.
	 */
	public RegisterDetail() {
	}

	/**
	 * REGIST_ID을 설정합니다..
	 * 
	 * @param registId
	 *            REGIST_ID
	 */
	public void setRegistId(Integer registId) {
		this.registId = registId;
	}

	/**
	 * REGIST_ID을 가져옵니다..
	 * 
	 * @return REGIST_ID
	 */
	public Integer getRegistId() {
		return this.registId;
	}

	/**
	 * REGIST_EMAIL을 설정합니다..
	 * 
	 * @param registEmail
	 *            REGIST_EMAIL
	 */
	public void setRegistEmail(String registEmail) {
		this.registEmail = registEmail;
	}

	/**
	 * REGIST_EMAIL을 가져옵니다..
	 * 
	 * @return REGIST_EMAIL
	 */
	public String getRegistEmail() {
		return this.registEmail;
	}

	/**
	 * REGIST_GENDER을 설정합니다..
	 * 
	 * @param registGender
	 *            REGIST_GENDER
	 */
	public void setRegistGender(String registGender) {
		this.registGender = registGender;
	}

	/**
	 * REGIST_GENDER을 가져옵니다..
	 * 
	 * @return REGIST_GENDER
	 */
	public String getRegistGender() {
		return this.registGender;
	}

	/**
	 * REGIST_IMG을 설정합니다..
	 * 
	 * @param registImg
	 *            REGIST_IMG
	 */
	public void setRegistImg(Blob registImg) {
		this.registImg = registImg;
	}

	/**
	 * REGIST_IMG을 가져옵니다..
	 * 
	 * @return REGIST_IMG
	 */
	public Blob getRegistImg() {
		return this.registImg;
	}

	/**
	 * REGIST_INTRO을 설정합니다..
	 * 
	 * @param registIntro
	 *            REGIST_INTRO
	 */
	public void setRegistIntro(String registIntro) {
		this.registIntro = registIntro;
	}

	/**
	 * REGIST_INTRO을 가져옵니다..
	 * 
	 * @return REGIST_INTRO
	 */
	public String getRegistIntro() {
		return this.registIntro;
	}


}
