package pojo.web.dto;
import java.io.Serializable;
import java.util.Date;
import java.util.Set;

/**
 * REGIST_HOUSE 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RegistHouse implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** RH_NO. */
	private Integer rhNo;
	
	/** CHECK_IN */
	private Date checkIn;
	
	/** CHECK_OUT */
	private Date checkOut;
	
	/** HOUSE */
	private House house;
	
	private Set<House> houseSet;

	public House getHouse() {
		return house;
	}

	public void setHouse(House house) {
		this.house = house;
	}

	public Set<House> getHouseSet() {
		return houseSet;
	}

	public void setHouseSet(Set<House> houseSet) {
		this.houseSet = houseSet;
	}

	public Date getCheckIn() {
		return checkIn;
	}

	public void setCheckIn(Date checkIn) {
		this.checkIn = checkIn;
	}

	public Date getCheckOut() {
		return checkOut;
	}

	public void setCheckOut(Date checkOut) {
		this.checkOut = checkOut;
	}

	/**
	 * 생성자.
	 */
	public RegistHouse() {
	}

	/**
	 * RH_NO을 설정합니다..
	 * 
	 * @param rhNo
	 *            RH_NO
	 */
	public void setRhNo(Integer rhNo) {
		this.rhNo = rhNo;
	}

	/**
	 * RH_NO을 가져옵니다..
	 * 
	 * @return RH_NO
	 */
	public Integer getRhNo() {
		return this.rhNo;
	}


}
