package pojo.web.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * REPLY 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Reply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** REPLY_NO. */
	private Integer replyNo;

	/** REPLY_CONTENT. */
	private String replyContent;

	/** REPLY_DATE. */
	private Date replyDate;

	/** MEMBER_ID. */
	private String memberId;

	/** DETAIL_ID. */
	private Integer detailId;

	/**
	 * 생성자.
	 */
	public Reply() {
	}

	/**
	 * REPLY_NO을 설정합니다..
	 * 
	 * @param replyNo
	 *            REPLY_NO
	 */
	public void setReplyNo(Integer replyNo) {
		this.replyNo = replyNo;
	}

	/**
	 * REPLY_NO을 가져옵니다..
	 * 
	 * @return REPLY_NO
	 */
	public Integer getReplyNo() {
		return this.replyNo;
	}

	/**
	 * REPLY_CONTENT을 설정합니다..
	 * 
	 * @param replyContent
	 *            REPLY_CONTENT
	 */
	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	/**
	 * REPLY_CONTENT을 가져옵니다..
	 * 
	 * @return REPLY_CONTENT
	 */
	public String getReplyContent() {
		return this.replyContent;
	}

	/**
	 * REPLY_DATE을 설정합니다..
	 * 
	 * @param replyDate
	 *            REPLY_DATE
	 */
	public void setReplyDate(Date replyDate) {
		this.replyDate = replyDate;
	}

	/**
	 * REPLY_DATE을 가져옵니다..
	 * 
	 * @return REPLY_DATE
	 */
	public Date getReplyDate() {
		return this.replyDate;
	}

	/**
	 * MEMBER_ID을 설정합니다..
	 * 
	 * @param memberId
	 *            MEMBER_ID
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * MEMBER_ID을 가져옵니다..
	 * 
	 * @return MEMBER_ID
	 */
	public String getMemberId() {
		return this.memberId;
	}

	/**
	 * DETAIL_ID을 설정합니다..
	 * 
	 * @param detailId
	 *            DETAIL_ID
	 */
	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	/**
	 * DETAIL_ID을 가져옵니다..
	 * 
	 * @return DETAIL_ID
	 */
	public Integer getDetailId() {
		return this.detailId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((replyNo == null) ? 0 : replyNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Reply other = (Reply) obj;
		if (replyNo == null) {
			if (other.replyNo != null) {
				return false;
			}
		} else if (!replyNo.equals(other.replyNo)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Reply [replyNo=" + replyNo + ", replyContent=" + replyContent + ", replyDate=" + replyDate
				+ ", memberId=" + memberId + ", detailId=" + detailId + "]";
	}

}
