package pojo.web.dto;
import java.io.Serializable;
import java.util.Date;

/**
 * REPORT 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Report implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** REPORT_NO. */
	private Integer reportNo;

	/** CATEGORY. */
	private String category;

	/** CONTENT. */
	private String content;

	/** REPORT_CUS_NAME. */
	private String reportCusName;

	/** REGIT_DATE. */
	private Date regitDate;
	
	/**  */

	/**
	 * 생성자.
	 */
	public Report() {
	}

	/**
	 * REPORT_NO을 설정합니다..
	 * 
	 * @param reportNo
	 *            REPORT_NO
	 */
	public void setReportNo(Integer reportNo) {
		this.reportNo = reportNo;
	}

	/**
	 * REPORT_NO을 가져옵니다..
	 * 
	 * @return REPORT_NO
	 */
	public Integer getReportNo() {
		return this.reportNo;
	}

	/**
	 * CATEGORY을 설정합니다..
	 * 
	 * @param category
	 *            CATEGORY
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * CATEGORY을 가져옵니다..
	 * 
	 * @return CATEGORY
	 */
	public String getCategory() {
		return this.category;
	}

	/**
	 * CONTENT을 설정합니다..
	 * 
	 * @param content
	 *            CONTENT
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * CONTENT을 가져옵니다..
	 * 
	 * @return CONTENT
	 */
	public String getContent() {
		return this.content;
	}

	/**
	 * REPORT_CUS_NAME을 설정합니다..
	 * 
	 * @param reportCusName
	 *            REPORT_CUS_NAME
	 */
	public void setReportCusName(String reportCusName) {
		this.reportCusName = reportCusName;
	}

	/**
	 * REPORT_CUS_NAME을 가져옵니다..
	 * 
	 * @return REPORT_CUS_NAME
	 */
	public String getReportCusName() {
		return this.reportCusName;
	}

	/**
	 * REGIT_DATE을 설정합니다..
	 * 
	 * @param regitDate
	 *            REGIT_DATE
	 */
	public void setRegitDate(Date regitDate) {
		this.regitDate = regitDate;
	}

	/**
	 * REGIT_DATE을 가져옵니다..
	 * 
	 * @return REGIT_DATE
	 */
	public Date getRegitDate() {
		return this.regitDate;
	}


}
