package pojo.web.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * REPORT 모델 클래스.
 * 
 * @author generated by ERMaster 
 * @version $Id$
 */
public class Report implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** REPORT_NO. */
	private Integer reportNo;

	/** REPORT_CATEGORY. */
	private String reportCategory;

	/** REPORT_CONTENT. */
	private String reportContent;

	/** REPORT_CUS_ID. */
	private String reportCusId;

	/** REGIT_DATE. */
	private Date regitDate;

	/**
	 * 생성자.
	 */
	public Report() {
	}

	/**
	 * REPORT_NO을 설정합니다..
	 * 
	 * @param reportNo
	 *            REPORT_NO
	 */
	public void setReportNo(Integer reportNo) {
		this.reportNo = reportNo;
	}

	/**
	 * REPORT_NO을 가져옵니다..
	 * 
	 * @return REPORT_NO
	 */
	public Integer getReportNo() {
		return this.reportNo;
	}

	/**
	 * REPORT_CATEGORY을 설정합니다..
	 * 
	 * @param reportCategory
	 *            REPORT_CATEGORY
	 */
	public void setReportCategory(String reportCategory) {
		this.reportCategory = reportCategory;
	}

	/**
	 * REPORT_CATEGORY을 가져옵니다..
	 * 
	 * @return REPORT_CATEGORY
	 */
	public String getReportCategory() {
		return this.reportCategory;
	}

	/**
	 * REPORT_CONTENT을 설정합니다..
	 * 
	 * @param reportContent
	 *            REPORT_CONTENT
	 */
	public void setReportContent(String reportContent) {
		this.reportContent = reportContent;
	}

	/**
	 * REPORT_CONTENT을 가져옵니다..
	 * 
	 * @return REPORT_CONTENT
	 */
	public String getReportContent() {
		return this.reportContent;
	}

	/**
	 * REPORT_CUS_ID을 설정합니다..
	 * 
	 * @param reportCusId
	 *            REPORT_CUS_ID
	 */
	public void setReportCusId(String reportCusId) {
		this.reportCusId = reportCusId;
	}

	/**
	 * REPORT_CUS_ID을 가져옵니다..
	 * 
	 * @return REPORT_CUS_ID
	 */
	public String getReportCusId() {
		return this.reportCusId;
	}

	/**
	 * REGIT_DATE을 설정합니다..
	 * 
	 * @param regitDate
	 *            REGIT_DATE
	 */
	public void setRegitDate(Date regitDate) {
		this.regitDate = regitDate;
	}

	/**
	 * REGIT_DATE을 가져옵니다..
	 * 
	 * @return REGIT_DATE
	 */
	public Date getRegitDate() {
		return this.regitDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((reportNo == null) ? 0 : reportNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Report other = (Report) obj;
		if (reportNo == null) {
			if (other.reportNo != null) {
				return false;
			}
		} else if (!reportNo.equals(other.reportNo)) {
			return false;
		}
		return true;
	}
<<<<<<< HEAD
	
	@Override
	public String toString() {
		return "Report [reportNo=" + reportNo + ", reportCategory=" + reportCategory + ", reportContent="
				+ reportContent + ", reportCusId=" + reportCusId + ", regitDate=" + regitDate + "]";
	}
=======
>>>>>>> branch 'master' of https://github.com/fiivehj55/special-adventure.git

}
